server:
  port: 7010
spring:
  datasource:
    url: jdbc:mysql://rm-2ze2b8l4g2174473e90130.mysql.rds.aliyuncs.com:3306/foodie_mysql_prd?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_bin&useServerPrepStmts=false&rewriteBatchedStatements=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: foodie
    password: ENC(IBjIOLt7v0tapxkJ0lDLIa4jnnEQjq07)
    druid:
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    hibernate.ddl-auto: none
    show-sql: true


logging:
  file: ./logs/prd/fooide-prd.log

application:
  payment:
    paypal:
      client-id: ENC(PTsNV6HdzoF2iGO5c0KZDiqImADIRzrg1/pFKdghJ5Wtomck7pLVHeoRzDSUm+mqjKCtFafkFAF/nHTPhgIldIiuE6x0rT848sd2+10Lbphlme+Q3Ffw3AhwsVkDIX5X)
      client-secret: ENC(BCAJrLjbRA0eadMIpiMFXowKdsDT1dkMzadWRgh17Rsri2z32NkVa193t/wAwQRFugHF7spcFKoQWlXR1wijt192fwY2LQHTdArdWgyzhCmq0Ck+105ECD3mmfDE8oes)
      mode: live
      activity-success-url: http://www.foodiepath.com/#/main/activity/success?orderno=%s
      activity-cancel-url: http://www.foodiepath.com/#/main/activity/cancel?orderno=%s
      restaurant-success-url: http://www.foodiepath.com/#/main/restaurant/success?orderno=%s
      restaurant-cancel-url: http://www.foodiepath.com/#/main/restaurant/cancel?orderno=%s