server:
  port: 7000
spring:
  datasource:
    url: jdbc:mysql://rm-2ze2b8l4g2174473e90130.mysql.rds.aliyuncs.com:3306/foodie_mysql?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_bin&useServerPrepStmts=false&rewriteBatchedStatements=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: foodie
    password: ENC(IBjIOLt7v0tapxkJ0lDLIa4jnnEQjq07)
    druid:
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    hibernate.ddl-auto: none
    show-sql: true


logging:
  file: ./logs/uat/fooide-uat.log


application:
  payment:
    paypal:
      client-id: ASgMRT2a5ZkDHd_PZUWGjjG7V40kFIFpmvefEpwfe8z94aBPyzwLHq1WCKNogfINQSDv5DhrVno11r6N
      client-secret: EKsOmilFgiYw15f3_6zXhkQnPtETUsgeael94E_D4awn3fTh7IzE_WWPqVQtG36hF5hOGZXusK1YCAoS
      mode: sandbox
      activity-success-url: http://www.uat.foodiepath.com/#/main/activity/success?orderno=%s
      activity-cancel-url: http://www.uat.foodiepath.com/#/main/activity/cancel?orderno=%s
      restaurant-success-url: http://www.uat.foodiepath.com/#/main/restaurant/success?orderno=%s
      restaurant-cancel-url: http://www.uat.foodiepath.com/#/main/restaurant/cancel?orderno=%s

