server:
  port: 7010
spring:
  datasource:
    url: jdbc:mysql://rm-2ze2b8l4g2174473e90130.mysql.rds.aliyuncs.com:3306/foodie_mysql_prd?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_bin&useServerPrepStmts=false&rewriteBatchedStatements=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: foodie
    password: ENC(IBjIOLt7v0tapxkJ0lDLIa4jnnEQjq07)
    druid:
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    hibernate.ddl-auto: none
    show-sql: true


logging:
  file: ./logs/fooide-prd.log

