spring.jpa.hibernate.ddl-auto: none
spring.datasource:
  url: jdbc:h2:file:~/h2/foodie
  driverClassName: org.h2.Driver
  username: sa


spring:
  kaptcha:
    enable: true
    properties:
      kaptcha.border: 'no'
      kaptcha.border.color: 105,179,90
      kaptcha.textproducer.font.color: blue
      kaptcha.image.width: "125"
      kaptcha.image.height: "55"
      kaptcha.textproducer.font.size: "45"
      kaptcha.session.key: KAPTCHA_SESSION_KEY
      kaptcha.textproducer.char.length: "4"
      kaptcha.textproducer.font.names: 宋体,楷体,微软雅黑
    suffix: suffix
