-- 排期表
ALTER TABLE FOODIE_ACTIVITY
    DROP COLUMN SERVICE_TIME;

CREATE TABLE IF NOT EXISTS FOODIE_SERVICE_SCHEDULING
(
    ID           varchar(32)  NOT NULL PRIMARY KEY,
    ACTIVITY_ID  VARCHAR(32) COMMENT '活动ID',
    SERVICE_DATE DATE COMMENT '排版日期',
    SHIFTS       TEXT COMMENT '时间段'
);
CREATE UNIQUE INDEX IDX_ACTIVITY_ID_DATE ON FOODIE_SERVICE_SCHEDULING (ACTIVITY_ID, SERVICE_DATE);


