CREATE TABLE FOODIE_WITHDRAWAL_ITEM
(
    ID          INT(11) NOT NULL COMMENT 'ID' PRIMARY KEY AUTO_INCREMENT,
    NAME        VARCHAR(50) COMMENT '名称',
    MERCHANT_ID VARCHAR(32) COMMENT '商家ID',
    AMOUNT      DOUBLE COMMENT '金额',
    CREATED_AT  TIMESTAMP COMMENT '创建时间'
);
