-- 修改文本内容长度
ALTER TABLE FOODIE_ACTIVITY modify DESCRIPTION longtext;

ALTER TABLE FOODIE_ARTICLE modify CONTENT longtext;

ALTER TABLE FOODIE_RESTAURANT modify CONTENT longtext;

ALTER TABLE FOODIE_PUBLIC_BENEFIT modify DESCRIPTION longtext;



