-- 排期表
ALTER TABLE FOODIE_ACTIVITY
    DROP COLUMN SERVICE_TIME;

CREATE TABLE IF NOT EXISTS FOODIE_SERVICE_SCHEDULING
(
    ID           VARCHAR(32) NOT NULL PRIMARY KEY COMMENT 'ID',
    ACTIVITY_ID  VARCHAR(32) NOT NULL COMMENT '活动ID',
    SERVICE_DATE DATE        NOT NULL COMMENT '排版日期',
    SHIFTS       VARCHAR(1000) COMMENT '时间段'
);
CREATE UNIQUE INDEX IDX_ACTIVITY_ID_DATE ON FOODIE_SERVICE_SCHEDULING (ACTIVITY_ID, SERVICE_DATE);


