-- 增加排序字段
ALTER TABLE FOODIE_ACTIVITY ADD COLUMN SORT INT COMMENT '排序字段';
ALTER TABLE FOODIE_ACTIVITY ADD COLUMN CREATED_AT TIMESTAMP NULL COMMENT '创建时间';

-- 设置为默认排序
UPDATE FOODIE_ACTIVITY SET SORT=999;


