CREATE TABLE FOODIE_MERCHANT_FEEDBACK
(
    ID          VARCHAR(32) NOT NULL COMMENT 'ID' PRIMARY KEY,
    TITLE       VARCHAR(255) COMMENT '反馈标题',
    CONTENT     TEXT COMMENT '反馈内容',
    MERCHANT_ID VARCHAR(32) COMMENT '商家ID',
    CREATED_AT  TIMESTAMP COMMENT '创建时间'
);

