CREATE TABLE FOODIE_FAVOURITE
(
    ID         INT(11) NOT NULL COMMENT 'ID' PRIMARY KEY AUTO_INCREMENT,
    OBJECT_ID  VARCHAR(32) COMMENT '收藏事物ID',
    TYPE       VARCHAR(20) COMMENT '收藏事物类型',
    USER_ID    VARCHAR(32) COMMENT '用户ID',
    CREATED_AT TIMESTAMP COMMENT '创建时间'
);

